import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Html, Preview, Text, Section, Hr,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = "GainEdge"

interface SignalAlertProps {
  symbol?: string
  direction?: string
  confidence?: number
  entry_price?: number | string
  take_profit?: number | string
  stop_loss?: number | string
  risk_reward?: string
  type?: string // "signal" or "live_trade"
}

const SignalAlertEmail = ({
  symbol = "XAUUSD",
  direction = "BUY",
  confidence = 8,
  entry_price,
  take_profit,
  stop_loss,
  risk_reward,
  type = "signal",
}: SignalAlertProps) => {
  const isBuy = direction === "BUY"
  const accentColor = isBuy ? "#00CFA5" : "#EF4444"
  const label = type === "signal" ? "⚡ New Signal" : "🔴 Live Trade"

  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>{label}: {symbol} {direction} — Confidence {confidence}/10</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={headerSection}>
            <Text style={brandText}>{SITE_NAME}</Text>
          </Section>

          {/* Alert badge */}
          <Section style={{ textAlign: 'center' as const, marginBottom: '20px' }}>
            <Text style={{ ...badge, backgroundColor: `${accentColor}20`, color: accentColor }}>
              {label}
            </Text>
          </Section>

          <Heading style={{ ...h1, color: accentColor }}>
            {symbol} — {direction}
          </Heading>

          <Text style={confidenceText}>
            Confidence: <span style={{ fontWeight: 'bold', color: '#1a1a2e' }}>{confidence}/10</span>
          </Text>

          {/* Trade details table */}
          {(entry_price || take_profit || stop_loss) && (
            <Section style={detailsBox}>
              {entry_price && (
                <Text style={detailRow}>
                  <span style={detailLabel}>Entry Price</span>
                  <span style={detailValue}>{entry_price}</span>
                </Text>
              )}
              {take_profit && (
                <Text style={detailRow}>
                  <span style={detailLabel}>Take Profit</span>
                  <span style={{ ...detailValue, color: '#00CFA5' }}>{take_profit}</span>
                </Text>
              )}
              {stop_loss && (
                <Text style={detailRow}>
                  <span style={detailLabel}>Stop Loss</span>
                  <span style={{ ...detailValue, color: '#EF4444' }}>{stop_loss}</span>
                </Text>
              )}
              {risk_reward && (
                <Text style={detailRow}>
                  <span style={detailLabel}>Risk:Reward</span>
                  <span style={detailValue}>{risk_reward}</span>
                </Text>
              )}
            </Section>
          )}

          <Hr style={hr} />

          <Text style={footer}>
            This alert was generated by RON, your {SITE_NAME} AI trading assistant.
            Always do your own analysis before entering a trade.
          </Text>
          <Text style={footerSmall}>
            You received this because you have email alerts enabled in your {SITE_NAME} settings.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: SignalAlertEmail,
  subject: (data: Record<string, any>) =>
    `${data.type === 'live_trade' ? '🔴' : '⚡'} ${data.symbol || 'Signal'} ${data.direction || ''} — ${SITE_NAME}`,
  displayName: 'Signal / Trade Alert',
  previewData: {
    symbol: 'XAUUSD',
    direction: 'BUY',
    confidence: 8,
    entry_price: 2345.50,
    take_profit: 2360.00,
    stop_loss: 2338.00,
    risk_reward: '1:2',
    type: 'signal',
  },
} satisfies TemplateEntry

// Styles
const main = { backgroundColor: '#ffffff', fontFamily: "'DM Sans', Arial, sans-serif" }
const container = { padding: '30px 25px', maxWidth: '480px', margin: '0 auto' }
const headerSection = { textAlign: 'center' as const, marginBottom: '24px' }
const brandText = {
  fontSize: '20px', fontWeight: 'bold' as const, color: '#00CFA5',
  letterSpacing: '2px', textTransform: 'uppercase' as const, margin: '0',
}
const badge = {
  display: 'inline-block', padding: '4px 14px', borderRadius: '20px',
  fontSize: '12px', fontWeight: 'bold' as const, letterSpacing: '1px',
  textTransform: 'uppercase' as const,
}
const h1 = {
  fontSize: '26px', fontWeight: 'bold' as const, textAlign: 'center' as const,
  margin: '0 0 8px', fontFamily: "'JetBrains Mono', monospace",
}
const confidenceText = {
  fontSize: '14px', color: '#55575d', textAlign: 'center' as const, margin: '0 0 24px',
}
const detailsBox = {
  backgroundColor: '#f8f9fb', borderRadius: '8px', padding: '16px 20px',
  border: '1px solid #e5e7eb',
}
const detailRow = {
  fontSize: '14px', color: '#55575d', margin: '6px 0',
  display: 'flex' as const, justifyContent: 'space-between' as const,
}
const detailLabel = { fontWeight: '500' as const }
const detailValue = {
  fontWeight: 'bold' as const, color: '#1a1a2e',
  fontFamily: "'JetBrains Mono', monospace",
}
const hr = { borderColor: '#e5e7eb', margin: '24px 0' }
const footer = { fontSize: '12px', color: '#999999', lineHeight: '1.5', margin: '0 0 8px' }
const footerSmall = { fontSize: '11px', color: '#bbbbbb', lineHeight: '1.4' }
